../src/cpu/cpu_wrap.sv
../src/cpu/rgu.sv
../src/cpu/marb.sv
../src/cpu/cpu_top.sv
../src/cpu/clkmnt.sv
../src/cpu/hzu.sv
../src/cpu/ifu.sv
../src/cpu/pfu.sv
../src/cpu/btb.sv
../src/cpu/idu.sv
../src/cpu/dec.sv
../src/cpu/rfu.sv
../src/cpu/csr.sv
../src/cpu/csr_alu.sv
../src/cpu/sru.sv
../src/cpu/alu.sv
../src/cpu/mdu.sv
../src/cpu/mul.sv
../src/cpu/div.sv
../src/cpu/tpu.sv
../src/cpu/dpu.sv
../src/cpu/amo.sv
../src/cpu/pmu.sv
../src/cpu/mpu_csr.sv
../src/cpu/mpu.sv
../src/cpu/mmu_csr.sv
../src/cpu/mmu.sv
../src/cpu/tlb.sv
../src/cpu/xmon.sv
../src/cpu/l1c.sv
../src/cpu/cfgreg.sv
../src/cpu/intc.sv
../src/cpu/clint.sv
../src/cpu/plic.sv
../src/cpu/dbgapb.sv
../src/cpu/util.sv
../src/peri/systimer.sv
../src/peri/uart.sv
../src/bus/iommu.sv
../src/bus/axi2mem_bridge.sv
../src/bus/axi2apb_bridge.sv
../src/bus/axi_5to4_biu.sv
../src/bus/axi_5to1_mux.sv
../src/bus/axi_1to4_dec.sv
../src/bus/axi_slice.sv
../mdl/sram.sv
../mdl/sram32x31.sv
../mdl/sram32x64.sv
../mdl/sram64x22.sv
../mdl/sram64x128.sv
+incdir+../include
