../src/cpu/cpu_wrap.sv
../src/cpu/rgu.sv
../src/cpu/dbg_axi_arb_2to1.sv
../src/cpu/peri_axi_arb_2to1.sv
../src/cpu/marb.sv
../src/cpu/cpu_top.sv
../src/cpu/clkmnt.sv
../src/cpu/hzu.sv
../src/cpu/ifu.sv
../src/cpu/pfu.sv
../src/cpu/btb.sv
../src/cpu/idu.sv
../src/cpu/dec.sv
../src/cpu/rfu.sv
../src/cpu/csr.sv
../src/cpu/csr_alu.sv
../src/cpu/sru.sv
../src/cpu/alu.sv
../src/cpu/mdu.sv
../src/cpu/mul.sv
../src/cpu/div.sv
../src/cpu/tpu.sv
../src/cpu/dpu.sv
../src/cpu/amo.sv
../src/cpu/pmu.sv
../src/cpu/mpu_csr.sv
../src/cpu/mpu.sv
../src/cpu/mmu_csr.sv
../src/cpu/mmu.sv
../src/cpu/tlb.sv
../src/cpu/xmon.sv
../src/cpu/l1c.sv
../src/cpu/cfgreg.sv
../src/cpu/cpustatreg.sv
../src/cpu/intc.sv
../src/cpu/clint.sv
../src/cpu/plic.sv
../src/cpu/dbgapb.sv
../src/cpu/util.sv
../src/cpu/peri.sv
../src/peri/systimer.sv
../src/peri/uart.sv
../src/peri/spi_core.sv
../src/peri/spi.sv
../src/peri/dma.sv
../src/dbg/dap.sv
../src/dbg/jtag_dp.sv
../src/dbg/apb_ap.sv
../src/dbg/apb_rx.sv
../src/dbg/axi_ap.sv
../src/dbg/axi_rx.sv
../src/dbg/mem_ap.sv
../src/bus/scu.sv
../src/bus/iommu.sv
../src/bus/axi2mem_bridge.sv
../src/bus/axi2apb_bridge.sv
../src/bus/axi_5to5_biu.sv
../src/bus/axi_5to1_mux.sv
../src/bus/axi_1to5_dec.sv
../src/bus/axi_2to1_mux_id8.sv
../src/bus/axi_2to1_mux_id9.sv
../src/bus/axi_slice.sv
../src/bus/apb_2to1_mux.sv
../src/bus/core_apb_conn.sv
../src/bus/intc_apb_conn.sv
../src/bus/peri_apb_conn.sv
../src/bus/spi_core_apb_conn.sv
../src/intf/apb_intf.sv
../src/intf/axi_intf.sv
../src/mem/rom32x2048.sv
../src/mem/sram.sv
../src/mem/sram32x31.sv
../src/mem/sram32x64.sv
../src/mem/sram64x22.sv
../src/mem/sram64x128.sv
+incdir+../include
+incdir+../rom
