../sim/test.sv
../src/cpu/cpu_wrap.sv
../src/cpu/marb.sv
../src/cpu/cpu_top.sv
../src/cpu/clkmnt.sv
../src/cpu/hzu.sv
../src/cpu/ifu.sv
../src/cpu/idu.sv
../src/cpu/dec.sv
../src/cpu/rfu.sv
../src/cpu/csr.sv
../src/cpu/sru.sv
../src/cpu/alu.sv
../src/cpu/tpu.sv
../src/cpu/dpu.sv
../src/cpu/pmu.sv
../src/cpu/mpu_csr.sv
../src/cpu/mpu.sv
../src/cpu/mmu_csr.sv
../src/cpu/mmu.sv
../src/cpu/tlb.sv
../src/cpu/l1c.sv
../src/cpu/intc.sv
../src/cpu/clint.sv
../src/cpu/plic.sv
../src/cpu/util.sv
../src/cpu/uart.sv
../src/bus/axi2mem_bridge.sv
../src/bus/mem2axi_bridge.sv
../src/bus/axi2apb_bridge.sv
../src/bus/axi_4to4_biu.sv
../src/bus/axi_4to1_mux.sv
../src/bus/axi_1to4_dec.sv
../src/bus/axi_slice.sv
../mdl/sram.sv
../mdl/sram32x31.sv
../mdl/sram32x64.sv
../mdl/sram64x22.sv
../mdl/sram64x128.sv
../mdl/cpu_tracer.sv

+incdir+../include

+nc64bit
+access+r
+define+FSDB
