# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/yutong/RISC-V_SoC/src/pynq-z2_v1.0.xdc

# XDC: /home/yutong/RISC-V_SoC/src/soc.sdc

# Block Designs: bd/soc/soc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc || ORIG_REF_NAME==soc} -quiet] -quiet

# IP: bd/soc/ip/soc_processing_system7_0_0/soc_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_processing_system7_0_0 || ORIG_REF_NAME==soc_processing_system7_0_0} -quiet] -quiet

# IP: bd/soc/ip/soc_axi_interconnect_0_0/soc_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_axi_interconnect_0_0 || ORIG_REF_NAME==soc_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/soc/ip/soc_smartconnect_0_0/soc_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_smartconnect_0_0 || ORIG_REF_NAME==soc_smartconnect_0_0} -quiet] -quiet

# IP: bd/soc/ip/soc_axi_apb_bridge_0_0/soc_axi_apb_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_axi_apb_bridge_0_0 || ORIG_REF_NAME==soc_axi_apb_bridge_0_0} -quiet] -quiet

# IP: bd/soc/ip/soc_cpu_wrap_0_0/soc_cpu_wrap_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_cpu_wrap_0_0 || ORIG_REF_NAME==soc_cpu_wrap_0_0} -quiet] -quiet

# IP: bd/soc/ip/soc_rst_ps7_0_50M_0/soc_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_rst_ps7_0_50M_0 || ORIG_REF_NAME==soc_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/soc/ip/soc_auto_pc_0/soc_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_auto_pc_0 || ORIG_REF_NAME==soc_auto_pc_0} -quiet] -quiet

# IP: bd/soc/ip/soc_auto_us_0/soc_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_auto_us_0 || ORIG_REF_NAME==soc_auto_us_0} -quiet] -quiet

# XDC: bd/soc/soc_ooc.xdc
