# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/yutong/RISC-V_SoC/vivado/soc/soc.cache/wt [current_project]
set_property parent.project_path /home/yutong/RISC-V_SoC/vivado/soc/soc.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/yutong/RISC-V_SoC [current_project]
update_ip_catalog
set_property ip_output_repo /home/yutong/RISC-V_SoC/vivado/soc/soc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/hdl/soc_wrapper.v
add_files /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/soc.bd
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_processing_system7_0_0/soc_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_smartconnect_0_0/bd_0/ip/ip_1/bd_9a87_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_smartconnect_0_0/bd_0/ip/ip_1/bd_9a87_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_smartconnect_0_0/bd_0/ip/ip_2/bd_9a87_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_smartconnect_0_0/bd_0/ip/ip_3/bd_9a87_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_smartconnect_0_0/bd_0/ip/ip_4/bd_9a87_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_smartconnect_0_0/bd_0/ip/ip_5/bd_9a87_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_smartconnect_0_0/bd_0/ip/ip_6/bd_9a87_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_smartconnect_0_0/bd_0/ip/ip_10/bd_9a87_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_smartconnect_0_0/bd_0/ip/ip_11/bd_9a87_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_smartconnect_0_0/bd_0/ip/ip_12/bd_9a87_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_smartconnect_0_0/bd_0/ip/ip_13/bd_9a87_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_smartconnect_0_0/bd_0/ip/ip_14/bd_9a87_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_smartconnect_0_0/bd_0/ip/ip_15/bd_9a87_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_smartconnect_0_0/bd_0/ip/ip_16/bd_9a87_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_smartconnect_0_0/bd_0/ip/ip_17/bd_9a87_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_smartconnect_0_0/bd_0/ip/ip_18/bd_9a87_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_smartconnect_0_0/bd_0/ip/ip_19/bd_9a87_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_smartconnect_0_0/bd_0/ip/ip_20/bd_9a87_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_smartconnect_0_0/bd_0/ip/ip_21/bd_9a87_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_smartconnect_0_0/bd_0/ip/ip_23/bd_9a87_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_smartconnect_0_0/bd_0/ip/ip_24/bd_9a87_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_smartconnect_0_0/bd_0/ip/ip_25/bd_9a87_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_smartconnect_0_0/bd_0/ip/ip_26/bd_9a87_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_smartconnect_0_0/bd_0/ip/ip_27/bd_9a87_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_smartconnect_0_0/bd_0/ip/ip_28/bd_9a87_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_axi_apb_bridge_0_0/soc_axi_apb_bridge_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_rst_ps7_0_50M_0/soc_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_rst_ps7_0_50M_0/soc_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_rst_ps7_0_50M_0/soc_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_auto_pc_0/soc_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_auto_us_0/soc_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_auto_us_0/soc_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_auto_us_0/soc_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/soc_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/yutong/RISC-V_SoC/src/pynq-z2_v1.0.xdc
set_property used_in_implementation false [get_files /home/yutong/RISC-V_SoC/src/pynq-z2_v1.0.xdc]

read_xdc /home/yutong/RISC-V_SoC/src/soc.sdc
set_property used_in_implementation false [get_files /home/yutong/RISC-V_SoC/src/soc.sdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top soc_wrapper -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_wrapper_utilization_synth.rpt -pb soc_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
