#!/bin/bash

filelist=${1};
outfile=${2};

rm -f ${outfile};
touch ${outfile};

echo   "/*-----------------------------------------------------*/" >> ${outfile};
printf "// %s is generated by %s\n" ${outfile} ${0}                >> ${outfile};
echo   "//"                                                        >> ${outfile};
printf "// %50s\n" $(date +"%Y-%m-%d %H:%M:%S")                    >> ${outfile};
echo   "/*-----------------------------------------------------*/" >> ${outfile};

while IFS= read -r line; do
    if [ -f "${line}" ]; then
        echo "" >> ${outfile};
        echo "/*--------------------------------------*/" >> ${outfile};
        echo "// FILE: ${line}" >> ${outfile};
        echo "/*--------------------------------------*/" >> ${outfile};
        echo "" >> ${outfile};
        cat "${line}" >> ${outfile};
    fi
done < "${filelist}"
