# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_auto_pc_0/soc_auto_pc_0.xci
# IP: The module: 'soc_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_auto_pc_0/soc_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_auto_pc_0/soc_auto_pc_0.xci
# IP: The module: 'soc_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_auto_pc_0/soc_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
